INSERT INTO TAG(NAME)
VALUES ('Отдых');
INSERT INTO TAG (NAME)
VALUES ('Пиво');
INSERT INTO TAG (NAME)
VALUES ('Учеба');
INSERT INTO TAG (NAME)
VALUES ('Творчество');
INSERT INTO TAG (NAME)
VALUES ('Хамовники');
INSERT INTO TAG (NAME)
VALUES ('Работа');
INSERT INTO TAG (NAME)
VALUES ('Мероприятие');
INSERT INTO TAG (NAME)
VALUES ('Важное');
INSERT INTO TAG (NAME)
VALUES ('Санкт-Петербург');
INSERT INTO TAG (NAME)
VALUES ('Москва');
INSERT INTO TAG (NAME)
VALUES ('Музеи');

INSERT INTO USER(USER_ID, TAGS)
VALUES (119443079, 'Хамовники,Пиво,Отдых')