INSERT INTO TAG(NAME)
VALUES ('Отдых');
INSERT INTO TAG (NAME)
VALUES ('Пиво');
INSERT INTO TAG (NAME)
VALUES ('Учеба');
INSERT INTO TAG (NAME)
VALUES ('Творчество');
INSERT INTO TAG (NAME)
VALUES ('Хамовники');
INSERT INTO TAG (NAME)
VALUES ('Работа');
INSERT INTO TAG (NAME)
VALUES ('Мероприятие');
INSERT INTO TAG (NAME)
VALUES ('Важное');
INSERT INTO TAG (NAME)
VALUES ('Санкт-Петербург');
INSERT INTO TAG (NAME)
VALUES ('Москва');
INSERT INTO TAG (NAME)
VALUES ('Музеи');

INSERT INTO USER(USER_ID)
VALUES (119443079);

INSERT INTO USER_TAG(USER_ID, TAG_NAME)
VALUES (119443079, 'Хамовники');
INSERT INTO USER_TAG(USER_ID, TAG_NAME)
VALUES (119443079, 'Пиво');
INSERT INTO USER_TAG(USER_ID, TAG_NAME)
VALUES (119443079, 'Отдых');